

-- 1  
SELECT K.MAMH,
  COUNT(CASE
	WHEN  K.KETQUA = 'Đạt' THEN 1 
    ELSE NULL END) AS SLDAT,
  COUNT(CASE 
	WHEN  K.KETQUA = 'Không đạt' THEN 1 
    ELSE NULL END) AS SLKHONGDAT
FROM th2qlgiaovu.ketquathi AS K
INNER JOIN th2qlgiaovu.hocvien AS H
ON K.MAHV = H.MAHV
GROUP BY K.MAMH;


    
    
-- 2
SELECT G.HOTEN, G.MAGV
FROM th2qlgiaovu.GIAOVIEN AS G
INNER JOIN th2qlgiaovu.GIANGDAY AS D
ON G.MAGV = D.MAGV
INNER JOIN th2qlgiaovu.LOP AS L
ON D.MAGV = L.MAGVCN
WHERE L.MAGVCN = (SELECT L1.MAGVCN
				FROM th2qlgiaovu.LOP AS L1
				WHERE L1.MAGVCN = G.MAGV)
GROUP BY G.HOTEN, G.MAGV
HAVING COUNT(D.MAGV) >= 1;

    
    
-- 3
	SELECT H.HO, H.TEN
	FROM th2qlgiaovu.hocvien AS H
	INNER JOIN th2qlgiaovu.LOP AS L
	ON H.MAHV = L.TRGLOP
	ORDER BY L.SISO DESC
	LIMIT 1;



-- 4 
	SELECT H.HO,H.TEN, K.KETQUA
    FROM th2qlgiaovu.hocvien AS H
    INNER JOIN TH2QLGIAOVU.LOP AS L
    ON H.MAHV = L.TRGLOP
    INNER JOIN th2qlgiaovu.ketquathi AS K
    ON L.TRGLOP = K.MAHV
    WHERE K.KETQUA = 'KHÔNG ĐẠT' AND K.LANTHI > 3
    GROUP BY H.HO,H.TEN,K.KETQUA;




SELECT H.MAHV, H.HO, H.TEN, COUNT(K.DIEM) AS 'DIEM 9,10'
FROM th2qlgiaovu.HOCVIEN AS H
INNER JOIN th2qlgiaovu.ketquathi AS K
ON H.MAHV = K.MAHV
WHERE K.DIEM IN ('9', '10')
GROUP BY H.MAHV, H.HO, H.TEN
ORDER BY 'DIEM 9,10' DESC
LIMIT 1;