
-- 1  
SELECT K.MAMH,
  COUNT(CASE
	WHEN  K.KETQUA = 'Đạt' THEN 1 
    ELSE NULL END) AS SLDAT,
  COUNT(CASE 
	WHEN  K.KETQUA = 'Không đạt' THEN 1 
    ELSE NULL END) AS SLKHONGDAT
FROM th2qlgiaovu.ketquathi AS K
INNER JOIN th2qlgiaovu.hocvien AS H
ON K.MAHV = H.MAHV
GROUP BY K.MAMH;

    
-- 2
SELECT G.HOTEN, G.MAGV
FROM th2qlgiaovu.GIAOVIEN AS G
INNER JOIN th2qlgiaovu.GIANGDAY AS D
ON G.MAGV = D.MAGV
INNER JOIN th2qlgiaovu.LOP AS L
ON D.MAGV = L.MAGVCN
WHERE L.MAGVCN = (SELECT L1.MAGVCN
				FROM th2qlgiaovu.LOP AS L1
				WHERE L1.MAGVCN = G.MAGV)
GROUP BY G.HOTEN, G.MAGV
HAVING COUNT(D.MAGV) >= 1;

    
    
-- 3
	SELECT H.HO, H.TEN
	FROM th2qlgiaovu.hocvien AS H
	INNER JOIN th2qlgiaovu.LOP AS L
	ON H.MAHV = L.TRGLOP
	ORDER BY L.SISO DESC
	LIMIT 1;



-- 4 
	SELECT H.HO,H.TEN, K.KETQUA
    FROM th2qlgiaovu.hocvien AS H
    INNER JOIN TH2QLGIAOVU.LOP AS L
    ON H.MAHV = L.TRGLOP
    INNER JOIN th2qlgiaovu.ketquathi AS K
    ON L.TRGLOP = K.MAHV
    WHERE K.KETQUA = 'KHÔNG ĐẠT' AND K.LANTHI > 3
    GROUP BY H.HO,H.TEN,K.KETQUA;



-- 5
SELECT H.MAHV, H.HO, H.TEN, COUNT(K.DIEM) AS 'DIEM 9,10'
FROM th2qlgiaovu.HOCVIEN AS H
INNER JOIN th2qlgiaovu.ketquathi AS K
ON H.MAHV = K.MAHV
WHERE K.DIEM IN ('9', '10')
GROUP BY H.MAHV, H.HO, H.TEN
ORDER BY 'DIEM 9,10' DESC
LIMIT 1;

-- 6 
SELECT LEFT(A.MAHV, 3) AS MALOP, A.MAHV, HV.HO, HV.TEN
FROM (
	SELECT K.MAHV, RANK()OVER(ORDER BY COUNT(K.MAMH) DESC) AS RANK_MH 
    FROM th2qlgiaovu.KETQUATHI AS K 
	WHERE K.DIEM BETWEEN 9 AND 10
	GROUP BY K.MAHV
) AS A 
INNER JOIN th2qlgiaovu.HOCVIEN AS HV
ON A.MAHV = HV.MAHV
WHERE A.RANK_MH BETWEEN 1 AND 3
GROUP BY MALOP, A.MAHV, HV.HO, HV.TEN;


-- 7
SELECT V.MAGV, G.HOCKY , G.NAM, COUNT(G.MAMH) AS MONHOC, COUNT(G.MALOP) AS LOPHOC 
FROM th2qlgiaovu.giangday AS G
INNER JOIN TH2QLGIAOVU.GIAOVIEN AS V
ON G.MAGV = V.MAGV
GROUP BY V.MAGV, G.HOCKY , G.NAM;



-- 8
SELECT V.MAGV, V.HOTEN
FROM th2qlgiaovu.giangday AS G
INNER JOIN TH2QLGIAOVU.GIAOVIEN AS V
ON G.MAGV = V.MAGV
WHERE G.HOCKY BETWEEN 1 AND 3  AND G.NAM BETWEEN 2022 AND 2023
GROUP BY V.MAGV,V.HOTEN
ORDER BY COUNT(G.MAMH) DESC, COUNT(G.MALOP) DESC 
LIMIT 1;


-- 9
SELECT K.MAMH, M.TENMH
FROM th2qlgiaovu.monhoc AS M
INNER JOIN th2qlgiaovu.ketquathi AS K
ON M.MAMH = K.MAMH 
WHERE K.KETQUA = 'KHÔNG ĐẠT' AND K.LANTHI = 1
GROUP BY K.MAMH,M.TENMH 
ORDER BY K.KETQUA DESC
LIMIT 1;


-- 10
SELECT H.MAHV, H.HO, H.TEN
FROM th2qlgiaovu.hocvien AS H
INNER JOIN th2qlgiaovu.ketquathi AS K
ON H.MAHV = K.MAHV
WHERE K.LANTHI = 1 AND EXISTS (
	SELECT *
    FROM th2qlgiaovu.MONHOC AS M
    WHERE K.MAMH = M.MAMH AND EXISTS(
		SELECT *
        FROM th2qlgiaovu.ketquathi AS K1 
        WHERE K1.MAHV = H.MAHV AND K1.MAMH = M.MAMH AND K1.LANTHI = 1 AND K1.KETQUA = 'ĐẠT'
    ) 
)
GROUP BY H.MAHV, H.HO, H.TEN
HAVING COUNT(K.KETQUA) = 4;



-- 11
SELECT K.MAHV, H.HO, H.TEN
FROM th2qlgiaovu.hocvien AS H
INNER JOIN th2qlgiaovu.ketquathi AS K
ON H.MAHV = K.MAHV
WHERE K.LANTHI = 1 AND EXISTS (
	SELECT *
    FROM th2qlgiaovu.MONHOC AS M
    WHERE K.MAMH = M.MAMH AND EXISTS (
		SELECT *
        FROM th2qlgiaovu.ketquathi AS K1
        WHERE K1.KETQUA = 'KHÔNG ĐẠT' AND K1.LANTHI = 1 AND H.MAHV = K1.MAHV AND K1.MAMH = M.MAMH
    )
)
GROUP BY K.MAHV, H.HO, H.TEN
HAVING COUNT(K.KETQUA) = 4;


-- 12
SELECT K3.MAHV , HV.HO , HV.TEN 
FROM (
	SELECT K.MAHV,COUNT(K.KETQUA) AS SODAT 
    FROM th2qlgiaovu.ketquathi AS K
	WHERE NOT EXISTS (
		SELECT 1 
		FROM th2qlgiaovu.ketquathi AS K1 
		WHERE K.MAHV = K1.MAHV AND K.MAMH = K1.MAMH AND K.LANTHI < K1.LANTHI
	) AND K.KETQUA = 'Dat'
	GROUP BY K.MAHV
	UNION
	SELECT K2.MAHV, COUNT(K2.MAMH) AS SOMH 
    FROM th2qlgiaovu.KETQUATHI AS K2  
	GROUP BY K2.MAHV
) AS K3 
INNER JOIN th2qlgiaovu.HOCVIEN AS HV
ON K3.MAHV = HV.MAHV
GROUP BY K3.MAHV , HV.HO , HV.TEN;


-- 13
SELECT H.MAHV, H.HO, H.TEN
FROM th2qlgiaovu.hocvien AS H
INNER JOIN th2qlgiaovu.ketquathi AS K
ON H.MAHV = K.MAHV
WHERE K.LANTHI = 1 AND EXISTS (
	SELECT *
    FROM th2qlgiaovu.MONHOC AS M
    WHERE K.MAMH = M.MAMH AND EXISTS(
		SELECT *
        FROM th2qlgiaovu.ketquathi AS K1 
        WHERE K1.MAHV = H.MAHV AND K1.MAMH = M.MAMH AND K1.LANTHI = 1 AND K1.KETQUA = 'ĐẠT'
    ) 
)
GROUP BY H.MAHV, H.HO, H.TEN
HAVING COUNT(K.KETQUA) = 4;


-- 14
SELECT K3.MAHV , HV.HO , HV.TEN 
FROM (
	SELECT K.MAHV,COUNT(K.KETQUA) AS SODAT 
    FROM th2qlgiaovu.ketquathi AS K
	WHERE NOT EXISTS (
		SELECT 1 
		FROM th2qlgiaovu.ketquathi AS K1 
		WHERE K.MAHV = K1.MAHV AND K.MAMH = K1.MAMH AND K.LANTHI < K1.LANTHI
	) AND K.KETQUA = 'Dat'
	GROUP BY K.MAHV
	UNION
	SELECT K2.MAHV, COUNT(K2.MAMH) AS SOMH 
    FROM th2qlgiaovu.KETQUATHI AS K2  
	GROUP BY K2.MAHV
) AS K3 
INNER JOIN th2qlgiaovu.HOCVIEN AS HV
ON K3.MAHV = HV.MAHV
GROUP BY K3.MAHV , HV.HO , HV.TEN;


-- 15
SELECT A.MAHV, HV.HO, HV.TEN 
FROM (
	SELECT K.MAMH, K.MAHV, K.DIEM, K1.DIEMMAX
	FROM TH2QLGIAOVU.KETQUATHI AS K 
		INNER JOIN (
		SELECT Q.MAMH, MAX(Q.DIEM) AS DIEMMAX 
        FROM TH2QLGIAOVU.KETQUATHI AS Q
		GROUP BY Q.MAMH
	) AS K1 
	ON K.MAMH = K1.MAMH
	WHERE NOT EXISTS (
			SELECT 1 FROM TH2QLGIAOVU.KETQUATHI AS K2 
			WHERE K.MAHV = K2.MAHV AND K.MAMH = K2.MAMH AND K.LANTHI < K2.LANTHI
	) AND K.DIEM = K1.DIEMMAX
) AS A 
INNER JOIN TH2QLGIAOVU.HOCVIEN AS HV
ON A.MAHV = HV.MAHV;








 